
server:
  port: ${CONFIG.PORT}
spring:
  cache:
    jcache:
      provider: com.hazelcast.cache.HazelcastCachingProvider
#      config: hazelcast.xml
  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/swallow
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/swallow
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 192.168.100.101
    port: 6379
    timeout: 3000
endpoints:
  shutdown:
    enabled: true
#    sensitive: false
#    id: swallow_1
management:
  context-path: /actuator/api

#management:
#  security:
#    enabled: false



